### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by Mancuerna**
Spanish translation for the README.md

Some of the terms are left in english for better understanding.

### CODE REVIEW

**Comment by Exslims** [comment]
Hello, thanks for the translating, we will update README in 30-45minutes, and need to translate a couple of sentences.

**Comment by Mancuerna** [comment]
I will translate those sentences tomorrow morning :)

**Comment by Mancuerna** [comment]
Done.

**Comment by Exslims** [comment]
Hm, i cant merge it because u translated README.md, i can try just copy ur commits to another file.

**Comment by Mancuerna** [comment]
Try now.

**Comment by Exslims** [comment]
I mean, it will erase the current file and leave only your)

**Comment by Mancuerna** [comment]
Then do as you said before. Copy&paste to another file 💃

**Comment by Exslims** [comment]
Added, thank you a lot for ur work.

**Pull request closed without merging**
