### PR TITLE
adding some CI integrations

### PR DESCRIPTION
**Pull request by Tyrael**
hi, I'm planning to contribute some more to this awesome project but I was surprised that there aren't any CI integrations in place.

I usually prefer travis so I started with that but then I realized that there are some jna methods which aren't supported on linux (I've marked one test windows only so that the build still passes on travis) so I also added appveyor integration because they have windows build machines with jdk and maven installed.

you can see the results of those builds here:
https://travis-ci.org/Tyrael/MercuryTrade/builds/478065375
https://ci.appveyor.com/project/Tyrael/mercurytrade/builds/21536454

### CODE REVIEW

**Comment by Exslims** [comment]
Hi, thank you, initially there was support Travis, but over time, I realized that it is not cost-effective because I did not want to pay for the assembly, now it can be done for free?

**Comment by Exslims** [comment]
now I'm not really engaged in development (only critical bugs) because I switched to a completely different stack of technologies and I have other plans, but improvements to the program from the community are welcome

**Comment by Tyrael** [comment]
yes, both travis and appveyor can be used for free of charge (both of these have paid plans for private repos ofc).

my original goal to extend MercuryTrade would be to introduce push notifications so that I can go afk but still receive the trade whispers on my phone and quickly jump back to the game when needed. I'm sure there would be many others who would welcome such a feature.

**Comment by Exslims** [comment]
sounds great

**Comment by Tyrael** [comment]
maybe you are aware but to enable the builds you have to visit https://travis-ci.org/Exslims/MercuryTrade and https://ci.appveyor.com/project/Exslims/mercurytrade/ and enable the build for this repo. let me know if you need help with that

**Comment by Exslims** [comment]
done

**Comment by Tyrael** [comment]
thanks!

**Pull request merged**
